#!/bin/sh

while [ "$1" ]; do

case "$1" in
-n)	unset len freq;;
-l|-f|\
-d|-D)	cmd="$1";;
*)	case "$cmd" in
	-l)	len="$1";;
	-f)	freq="$1";;
	-d|-D)	freq=0 ; len="$1";;
	esac
	[ -n "$len" -a -n "$freq" ] && echo "$len	$freq"
	;;
esac
shift
done >/sys/devices/platform/pcspkr/buzzer
