#!/bin/bash

while read note time; do

ottava=3

case $note in
*0|*1|*2|*3|*4|*5|*6|*7|*8|*9)	ottava=${note:(-1)}
				note=${note:0:$((${#note}-1))}
				;;
esac

note=${note/\#/d}

ottava=$((ottava-3))

case $note in
La	|A		) freq=440;;
Lad	|Ad	|Bb	) freq=466;;
Si	|B		) freq=494;;
Do	|C		) freq=523;;
Dod	|Cd	|Db	) freq=554;;
Re	|D		) freq=587;;
Red	|Dd	|Eb	) freq=622;;
Mi	|E		) freq=659;;
Fa	|F		) freq=698;;
Fad	|Fd	|Gb	) freq=740;;
Sol	|G		) freq=784;;
Sol	|Gd	|Ab	) freq=831;;
P			) freq=0;;
esac

i=$ottava
if [ $ottava -gt 0 ]; then 
	while [ $i -gt 0  ]; do
		freq=$((freq * 2))
		i=$((i-1))
	done
else
	while [ $i -lt 0  ]; do
		freq=$((freq / 2))
		i=$((i+1))
	done
fi

echo "$((time * 100)) $freq"

done
